// Re-export all shared types — import from '@synapse/shared' in both apps
export type {
  // Enums
  NodeCategory,
  NodeStatus,
  NodePriority,
  EffortUnit,
  EdgeType,
  ConflictSeverity,
  SnapshotTrigger,
  // Entities
  User,
  Project,
  Map,
  ShareConfig,
  ViewportState,
  NodeFilterState,
  Node,
  Edge,
  Snapshot,
  SnapshotData,
  ChangeLog,
  // Computed
  Conflict,
  ConflictChainNode,
  CriticalPathResult,
  NodeSuggestion,
  ResolutionStrategy,
  ResolutionOperation,
} from '../../../../docs/contracts/entities'

export type {
  // API contracts
  ApiSuccess,
  ApiError,
  PaginatedResponse,
  RegisterRequest,
  LoginRequest,
  AuthResponse,
  CreateProjectRequest,
  UpdateProjectRequest,
  CreateMapRequest,
  UpdateMapRequest,
  MapDetailResponse,
  SharedMapResponse,
  CreateNodeRequest,
  UpdateNodeRequest,
  BulkUpdateNodesRequest,
  NodeMutationResponse,
  CreateEdgeRequest,
  UpdateEdgeRequest,
  CreateSnapshotRequest,
  SnapshotDiff,
  CategorizationRequest,
  CategorizationResponse,
  SuggestionRequest,
  SuggestionResponse,
  NlToMapRequest,
  NlToMapResponse,
  ConflictResolutionRequest,
  ConflictResolutionResponse,
  ExportPdfRequest,
  ExportImageRequest,
} from '../../../../docs/contracts/api'
